server:
  port: 80

spring:
  application:
    name: cloud-hystrix-consumer-service

  devtools:
    livereload:
      port: 30085
    restart:
      poll-interval: 3s

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: cloud-hystrix-consumer-service-80

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true