server:
  port: 7002

spring:
  application:
    name: eureka-server-7002

  devtools:
    restart:
      poll-interval: 3s
    livereload:
      port: 37002

eureka:
  instance:
    hostname: eureka7002.com

  server:
    # 关闭自我保护机制，保证不可用服务及时剔除
    enable-self-preservation: true
    # 主动检测并剔除无效服务的间隔时间
    eviction-interval-timer-in-ms: 5000

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka