server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  devtools:
    restart:
      poll-interval: 3s
    livereload:
      port: 38001

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.daistudy.springcloud.common.entity

eureka:
  client:
    service-url:
      # 集群时，指向多个 eureka server
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 单机时，指向一个 eureka server
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment-8001
    prefer-ip-address: true
    # 主动发送心跳包的间隔时间
    lease-renewal-interval-in-seconds: 2
    # 服务过期时间，EurekaServer超过这个时间没有接收到心跳就会将这个实例剔除，一般是lease-renewal-interval-in-seconds的3倍
    lease-expiration-duration-in-seconds: 6