spring:
  application:
    name: client
eureka:
  client:
    service-url:
      # 服务端也会向客户端发送心跳包？？？
      # 服务端和客户端通过心跳检查的机制进行交互
      # Eureka 客户端每个一段时间向这个地址发送一次心跳包（请求数据），如果发现 Eureka 服务器是启动状态，客户端就会重新注册到注册中心
      # 可以添加多个注册中心地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
