server:
  port: 80

spring:
  application:
    name: cloud-order-service

  devtools:
    restart:
      poll-interval: 3s
    livereload:
      port: 30083

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}