server:
  port: 80

spring:
  application:
    name: cloud-order-service

  devtools:
    restart:
      poll-interval: 3s
    livereload:
      port: 30082

  cloud:
    zookeeper:
      connect-string: localhost:2181
